apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-webapp
spec:
  destination:
    namespace: github-webapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/CMarquetand/webapp-k8s.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true